on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # - uses: denoland/setup-deno@v2
      #   with:
      #     deno-version: v2.x
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          nix develop
          deno task build
      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./_site --project-name=blog --commit-dirty=true
