name: concurrency test A (literal true)
on: pull_request
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  queue: max
  cancel-in-progress: true
jobs:
  sleep:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 90
