name: concurrency test C (job-level queue)
on: pull_request
jobs:
  sleep:
    runs-on: ubuntu-latest
    concurrency:
      group: concurrency-test-c-${{ github.ref }}
      queue: max
    steps:
      - run: sleep 90
