name: concurrency test B (expression)
on: pull_request
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  queue: max
  cancel-in-progress: ${{ github.event_name == 'workflow_dispatch' }}
jobs:
  sleep:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 90
